[package]
name = "prosic"
version = "2.0.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]

[dependencies]
libprosic = { git = "https://github.com/prosic/libprosic" }
clap = {version = "2.9.*", features = ["yaml", "color", "suggestions"]}
rust-htslib = { git="https://github.com/rust-bio/rust-htslib.git" }
log = "0.3.*"
fern = "0.3.*"
csv = "0.14.*"
itertools = "0.4.*"
time = "*"
flame = { version = "^0.1.2", optional = true }
flamer = { version = "^0.1.2", optional = true }

[features]
default = []
flame_it = ["flame", "flamer", "libprosic/flame_it"]
